### ISSUE TITLE
Questions and Doubts

### ISSUE THREAD

**Issue by AlanPadi95** [Flying-Free/ansible-role-openproject#1]
## 1. How many instances of the database will we need?

```yml
production:
  adapter:  postgresql
  host:     {{ openproject_postgres.host }}
  database: {{ openproject_postgres.name }}
  username: {{ openproject_postgres.user }}
  password: {{ openproject_postgres.pass }}
  encoding: utf8

development:
  adapter:  postgresql
  host:     localhost
  database: openproject_dev
  username: openproject
  password: openproject
  encoding: utf8

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test:
  adapter:  postgresql
  host:     localhost
  database: openproject_test
  username: openproject
  password: openproject
  encoding: utf8
```

## 3. Email method (SMTP?)
